### ISSUE TITLE
GET USEFUL FEEDBACK IF SOMETHING GOES WRONG

### ISSUE THREAD

**Issue by lyndseysc** [FACxBeamery/Week5#1]

**Comment by arrested-developer** [comment]
Agreed! I'm having a hard time submitting a resource because your front-end hasn't told me what is required, and your backend isn't sending back a message that tells me what went wrong. Try to send back a helpful message from the server to the client when there is a 400 error.

**Comment by lyndseysc** [comment]
fix with ae1a87d
