### ISSUE TITLE
HTML missing <main> tag

### ISSUE THREAD

**Issue by teenie-quaggard** [FACxBeamery/Week5#24]
A very small issue...but don't forget to use the `<main role="main">` tag in your HTML!
This is mainly for accessibility purposes and doesn't affect the DOM structure of the page.
I've also just learned that the attribute `role="main"` should be used for cross-browser support. :)

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/main

**Comment by lyndseysc** [comment]
182230e
 fixed :)
