### ISSUE TITLE
Small capitalisation typo in name on line 20 of HTML

### ISSUE THREAD

**Issue by teenie-quaggard** [FACxBeamery/Week5#27]
![Screen Shot 2019-10-11 at 09 57 29](https://user-images.githubusercontent.com/37771591/66638819-9892d380-ec0d-11e9-9ae5-6ef571ee6504.png)
Easy fix! 
topictoFind vs topicToFind

**Comment by teenie-quaggard** [comment]
Same problem on line 35.
![Screen Shot 2019-10-11 at 09 59 18](https://user-images.githubusercontent.com/37771591/66638957-d4c63400-ec0d-11e9-8c53-66c2762351c2.png)

**Comment by lyndseysc** [comment]
fixed with 182230e
