### ISSUE TITLE
You've got tests! 👩🏻‍🔬

### ISSUE THREAD

**Issue by arrested-developer** [FACxBeamery/Week5#29]
It's great to see that you're testing your database queries 🎉

Use a different database URL for your tests, so that you can destroy and rebuild it without affecting your demo data.

You can set and use the NODE_ENV environment variable to indicate whether you are in a "test", "development" or "production" environment.

You can also set your database URLs using environment variables - this will help prepare for deploying your app

**Comment by TKostrzewski** [comment]
Issue partially resolved in:
https://github.com/FACxBeamery/Week5/pull/47/commits/d2869dee249485d926b85d4e16571d8a92cf3360

The test database has been created but I didn't manage to do the work with the environment variables.
