### ISSUE TITLE
Commits

### ISSUE THREAD

**Issue by teenie-quaggard** [FACxBeamery/Week5#30]
I'm not sure if you've seen this page before, you can find it on the Insights tab on Github. It shows how many commits you each have done.

Obviously, this isn't a strict rule, but when you are working on these group projects, try to commit (roughly) evenly! This shows the mentors that you are switching pairing types.

![Screen Shot 2019-10-11 at 10 03 35](https://user-images.githubusercontent.com/37771591/66639472-cb899700-ec0e-11e9-8e0e-140d26dbeb20.png)

**Comment by lyndseysc** [comment]
it's about even now! the middle and right user are both me, something about my ssh key recognises its my name but doesn't link it to my github account!
