### ISSUE TITLE
Naming your tests

### ISSUE THREAD

**Issue by teenie-quaggard** [FACxBeamery/Week5#33]
Hey! Great to see that you have a few tests! 👏 

It would be great to see some more descriptive names for them. For example, "async test 1" doesn't tell me much about what is happening in that test.

**Comment by TKostrzewski** [comment]
Issue resolved in:
https://github.com/FACxBeamery/Week5/pull/46/commits/64a17c462b89fa6da74a04cdc5319c0067768fd8

The tests were renamed to reflect what they actually do.
