### ISSUE TITLE
Reset form on submit 

### ISSUE THREAD

**Issue by marthaklambert** [FACxBeamery/Week5#36]
If a topic is not found, the previous topic information remains on the page, could you reset this?
The text in the form is also still there- could you remove this on submit?

**Comment by TKostrzewski** [comment]
Issue resolved in:
https://github.com/FACxBeamery/Week5/pull/44/commits/97f4e221700228cbe1247bd170a2429d56926bae

After the message pops up telling the user that no resource exists for that topic, the value of the topic field is set to "".
